### PR TITLE
Added Bootstrap 4 and Twitter widget

### PR DESCRIPTION
**Pull request by julianmangut**

### CODE REVIEW

**Comment by lRaulMN7** [comment]
I'll review it later. I'm in the process to add Angular 2 which will include Bootstrap 3, but your code will help :) :heart: :studio_microphone: :package: @julianmangut

**Comment by julianmangut** [comment]
Bootstrap 3¿? Why not Bootstrap 4¿?

**Comment by lRaulMN7** [comment]
> Bootstrap 3¿? Why not Bootstrap 4¿?

Because I'm following a tutorial and I want to stick on what the guy is using. We can jump to Bootstrap 4 in the future. What do you think? @julianmangut

**Comment by julianmangut** [comment]
I think that follow something that is older is not the best idea... I can teach you Bootstrap 4 if you want and we follow with this pull...

**Comment by lRaulMN7** [comment]
I think I'll be accepting this pull request by the end of this week. Already got my hands into bootstrap 4 and it's going great :-) @julianmangut

**Comment by tato** [comment]
> I think I'll be accepting this pull request by the end of this week. 

😡🤬

**Comment by tato** [comment]
wow! great job!

**Pull request merged**
